### ISSUE TITLE
Messages not arriving after leaving airplane mode

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-ios#2387]
A user complaining about missing notifications again:

- iOS version: 16.7.10
- Device:
- Delta Chat version: 1.46.5
- Expected behavior: After removing the device from airplane mode, notifications for messages that were sent in the meantime are received.
- Actual behavior: After removing the device from airplane mode, no notifications arrive.
- Steps to reproduce the problem:
  - Set the device to airplane mode
  - Wait until someone sent you a message
  - Remove the device from airplane mode

Not sure if this is a known problem, but since I couldn't find an existing issue for this, I simply created one

**Comment by r10s** [comment]
> After removing the device from airplane mode, notifications for messages that were sent in the meantime are received

usually this is what happens, i just double checked that this is not a general issue:

https://github.com/user-attachments/assets/ed9d58d8-b2ff-48bc-aaeb-509e588fc2c8

however, also some [notification issues](https://github.com/deltachat/deltachat-ios/pulls?q=is%3Apr+is%3Aclosed+label%3Anotify+) were fixed from 1.46 to 1.48, so this needs a retry or more detailed information.

other common reasons for missing notifications are multi-device, battery- or data-saving modes. also, note sure for how long apple keeps a notification if devices are offline

**Comment by r10s** [comment]
closing, there is also a new testflight, and a new release probably soon (1.48.4); please reopen, ideally with additional information, if the issue persists

**Comment by Hocuri** [comment]
It's still happening, here is a log:

<details><summary>Details</summary>
<p>


```
iosVersion=16.7.10
any-database-encrypted=false
notify-token=dd8ff39dbce8deb643576db9e1c2784251af41088311ae30c4cf9c56461e54c1
backgroundRefreshStatus=denied
DEBUG=0

arch=64
authserv_id_candidates=nine.testrun.org
bcc_self=1
blobdir=/private/var/mobile/Containers/Shared/AppGroup/***/accounts/e618dba9-7878-45e7-b65c-a3d1748a5c17/dc.db-blobs
bot=0
configured_inbox_folder=INBOX
configured_mvbox_folder=DeltaChat
configured_sentbox_folder=<unset>
configured_trash_folder=<unset>
database_dir=/private/var/mobile/Containers/Shared/AppGroup/****/accounts/e618dba9-7878-45e7-b65c-a3d1748a5c17/dc.db
database_encrypted=false
database_version=123
debug_logging=0
delete_device_after=0
delete_server_after=0
delete_to_trash=<unset>
deltachat_core_version=v1.148.6
disable_idle=false
displayname=***
download_limit=0
e2ee_enabled=1
entered_account_settings=*********@nine.testrun.org imap:unset:***:unset:0:Automatic:AUTH_NORMAL smtp:unset:0:unset:0:Automatic:AUTH_NORMAL cert_automatic
fetch_existing_msgs=0
fetched_existing_msgs=true
fingerprint=****
fix_is_chatmail=false
folders_configured=5
gossip_period=172800
imap_server_admin="mailto:root@nine.testrun.org"
imap_server_comment="Chatmail server"
imap_server_id={"name": "Dovecot"}
is_chatmail=true
is_configured=1
is_muted=false
journal_mode=wal
key_gen_type=0
last_cant_decrypt_outgoing_msgs=0
last_housekeeping=1732623729
last_msg_id=742
level=awesome
mdns_enabled=1
media_quality=0
messages_in_contact_requests=0
mvbox_move=1
num_cpus=6
number_of_chat_messages=590
number_of_chats=13
number_of_contacts=7
only_fetch_mvbox=0
private_key_count=1
private_tag=<unset>
proxy_enabled=0
public_key_count=7
quota_exceeding=0
save_mime_headers=false
scan_all_folders_debounce_secs=60
secondary_addrs=
selfavatar=/private/var/mobile/Containers/Shared/AppGroup/CB73A4CE-D669-4F07-9797-3EAC8CFB084E/accounts/e618dba9-7878-45e7-b65c-a3d1748a5c17/dc.db-blobs/tempAvatar-3505059480.jpg
sentbox_watch=0
show_emails=2
sign_unencrypted=0
sqlite_version=3.45.3
sync_msgs=1
uptime=0h 4m 42s
used_account_settings=*********@nine.testrun.org imap:[nine.testrun.org:993:tls:*********@nine.testrun.org] smtp:[nine.testrun.org:465:tls:*********@nine.testrun.org] provider:none cert_strict
verified_one_on_one_chats=true
webrtc_instance=<unset>
webxdc_realtime_enabled=true

notify-timestamps=15:55 16:35 17:16 
notify-fetch-info=
[21:00] ABORT1 
[21:01] ⏸️ 
[22:10] ▶️ 📡 ▶️ ▶️ OK3 0.426s 
[22:11] ⏸️ 
[22:36] ▶️ 📡 ▶️ ▶️ OK3 0.325s ⏸️ 
[22:48] ▶️ ▶️ ⏸️ 
[23:00] 🤜 OK1 1 2.069s 🤜 ▶️ OK1 1 4.639s ▶️ 
[23:02] ⏸️ 
[00:58] ▶️ ▶️ 📡 ABORT1 
[01:00] ⏸️ 
[10:11] ▶️ ▶️ 📡 ABORT1 
[10:12] ⏸️ 
[11:08] ▶️ ▶️ 📡 ABORT1 
[11:09] ▶️ ▶️ 
[11:11] ⏸️ 
[11:27] 🤜 OK0 0.614s 🤜 OK1 1 0.581s 
[11:35] ▶️ ▶️ 📡 ABORT1 
[11:36] ⏸️ 
[14:21] 🤜 OK1 1 8.095s 
[14:42] 🤜 OK1 1 1.331s 🤜 OK1 1 1.038s 
[14:48] 🤜 OK1 1 0.715s ▶️ ▶️ 📡 ABORT1 ▶️ ▶️ 
[14:52] ⏸️ ▶️ ▶️ 
[14:53] ⏸️ 
[14:55] ▶️ ▶️ ⏸️ 
[16:13] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[18:06] ▶️ ▶️ 📡 ABORT1 
[18:07] ⏸️ 
[18:40] ▶️ ▶️ ⏸️ 
[21:08] ▶️ ▶️ 📡 ABORT1 
[21:11] ⏸️ 
[11:08] ▶️ ▶️ 📡 ABORT1 
[11:09] ⏸️ 
[11:13] ▶️ ▶️ ⏸️ 
[11:44] ▶️ ▶️ 📡 ABORT1 
[11:45] ▶️ ⏸️ ▶️ ▶️ ⏸️ ▶️ ▶️ 
[11:49] 📡 ABORT1 
[11:50] ⏸️ ▶️ ▶️ 
[11:52] ⏸️ 
[11:56] 🤜 OK1 1 1.570s 
[12:21] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:05] ▶️ ▶️ 📡 ABORT1 
[13:06] ⏸️ 
[13:16] ▶️ ▶️ ⏸️ 
[13:32] ▶️ ▶️ 📡 ABORT3 ⏸️ 
[13:47] ▶️ ▶️ 
[13:48] 📡 ABORT1 
[13:50] ⏸️ 
[01:21] ▶️ ▶️ 📡 ABORT3 ⏸️ 
[01:37] ▶️ ▶️ ⏸️ 
[15:21] ▶️ ▶️ 📡 ABORT1 
[15:23] ⏸️ 
[16:27] ▶️ ▶️ 📡 ABORT1 
[16:30] ⏸️ 
[16:52] ▶️ ▶️ 📡 ABORT1 
[16:55] ▶️ ▶️ ▶️ ▶️ 📡 ABORT1 
[16:56] ⏸️ 
[16:57] ▶️ ▶️ 
[16:59] ⏸️ 
[17:00] ⏸️ 
[18:00] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[18:46] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[19:12] 🤜 OK1 1 0.632s 🤜 OK1 1 0.379s 
[19:13] 🤜 OK1 1 0.521s 
[21:27] ▶️ ▶️ 📡 ABORT1 
[21:29] ⏸️ 
[21:44] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[21:56] ▶️ ▶️ ⏸️ 
[22:00] ▶️ ▶️ 📡 ABORT1 
[22:01] ⏸️ ▶️ ▶️ ⏸️ 
[22:08] ▶️ ▶️ 
[22:09] ⏸️ 
[22:16] ▶️ ▶️ ⏸️ 
[22:20] ▶️ ▶️ ⏸️ 
[22:41] ▶️ ▶️ 📡 ABORT1 
[22:42] ⏸️ 
[22:56] ▶️ ▶️ 
[22:57] 📡 ABORT3 ▶️ ▶️ 🤜 ABORT4 ⏸️ 
[23:00] ▶️ ▶️ ⏸️ 🤜 OK1 1 1.101s ▶️ ▶️ 
[23:01] ⏸️ 
[08:36] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[11:40] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[11:58] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[12:20] ▶️ ▶️ 
[12:21] 📡 ABORT1 
[12:22] ▶️ ▶️ 
[12:23] ⏸️ 
[12:29] ▶️ ▶️ ⏸️ 
[12:50] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:11] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:39] 🤜 OK1 2 0.541s 🤜 
[13:40] OK0 0.227s 
[13:41] ▶️ 📡 ▶️ ▶️ OK3 0.112s 
[13:43] ⏸️ 
[14:40] ▶️ ▶️ ⏸️ 
[16:46] ▶️ ▶️ 📡 ABORT1 
[16:50] 📡 ABORT1 
[16:54] ⏸️ 
[16:57] 🤜 OK1 1 0.531s 🤜 OK0 0.416s 🤜 OK0 0.415s 🤜 OK0 0.392s ▶️ ▶️ 
[16:59] 🤜 ABORT4 
[17:00] ⏸️ 
[17:01] ▶️ ▶️ 
[17:02] ▶️ ▶️ 
[17:03] ⏸️ 
[17:12] ▶️ ▶️ 
[17:13] ▶️ ▶️ 
[17:14] ▶️ ▶️ 
[17:16] ▶️ ▶️ 
[17:17] ⏸️ 
[17:18] 🤜 OK1 1 0.439s 🤜 OK1 1 0.382s ▶️ ▶️ 
[17:19] 🤜 ABORT4 
[17:22] ⏸️ 
[17:27] 🤜 OK1 1 1.009s 
[17:28] ▶️ ▶️ 
[17:30] ⏸️ 
[17:31] ▶️ ▶️ ⏸️ 
[17:36] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[17:39] ▶️ ▶️ ⏸️ 
[23:52] ▶️ ▶️ 📡 ABORT1 
[23:59] ⏸️ 
[00:01] ▶️ ▶️ ⏸️ 
[00:19] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[08:11] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[09:01] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[09:38] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:22] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:27] 🤜 OK1 1 0.776s 
[13:28] ▶️ ▶️ 📡 ABORT1 
[13:29] ⏸️ 
[13:35] ▶️ ▶️ 
[13:36] ⏸️ 
[13:40] 🤜 OK1 1 0.407s 
[13:42] ▶️ ▶️ 
[13:43] ⏸️ 
[13:49] 🤜 OK1 1 3.712s 
[13:51] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[13:54] ▶️ ▶️ 
[13:55] ⏸️ 
[14:08] ▶️ ▶️ 📡 ABORT1 
[14:09] ⏸️ 
[15:11] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[15:25] ▶️ ▶️ 📡 ABORT1 
[15:28] ▶️ 
[15:31] ⏸️ 
[15:55] ▶️ 📡 ▶️ ▶️ OK3 0.224s ⏸️ 
[16:21] 🤜 OK1 1 0.826s 
[16:35] ▶️ 📡' ▶️ 📡 ABORT3 ⏸️ OK3 0.446s 
[16:36] ▶️ ▶️ ⏸️ 
[16:40] ▶️ ▶️ ⏸️ 
[16:48] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[17:16] ▶️ 📡 ▶️ ▶️ OK3 0.083s ⏸️ 
[17:29] ▶️ ▶️ 📡 ABORT1 ⏸️ 
[18:10] ▶️ ▶️ 📡 ABORT1 
[18:11] ⏸️ 
[18:16] 🤜 OK1 1 0.431s 
[18:31] ▶️ ▶️ ⏸️ 
[18:33] ▶️ ▶️ 
[18:34] 📡 ABORT1 
[18:37] ⏸️ 
[18:39] ▶️ ▶️ ⏸️ 
[18:40] ▶️ ▶️ 
[18:41] ⏸️ 
[18:52] ▶️ ▶️ 📡 ABORT3 ⏸️ 
[18:53] ▶️ ▶️ ⏸️ 
[18:59] 🤜 OK1 1 0.424s 
[19:00] 🤜 OK1 1 0.534s 
[19:18] ▶️ ▶️ 📡 ABORT1 
[19:19] ⏸️ 
[21:57] ▶️ ▶️ 📡 ABORT1 
[21:58] ⏸️ 
[22:14] ▶️ ▶️ 📡 ABORT1 
[22:15] ⏸️ 
[22:24] ▶️ ▶️ 
[22:25] 📡 ABORT1 ⏸️ 
[22:29] ▶️ ▶️ 

[26.11.2024, 22:24] 💙 ➡️ didFinishLaunchingWithOptions
[26.11.2024, 22:24] 💙 ➡️ event emitter started
[26.11.2024, 22:24] 💙 [1] src/securejoin.rs:131: Generated QR code.
[26.11.2024, 22:24] 💙 [1] src/securejoin.rs:131: Generated QR code.
[26.11.2024, 22:24] 💙 ⏰ getChatlist: 0.001071929931640625 s
[26.11.2024, 22:24] 💙 [1] src/chat.rs:4367: Device-message update_1_46e_ios already added.
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:66: starting IO
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:389: starting inbox loop
[26.11.2024, 22:24] 💙 [1] src/imap.rs:327: Connecting to IMAP server
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:699: starting simple loop for Mvbox
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:756: Starting SMTP loop.
[26.11.2024, 22:24] 💙 [1] src/imap.rs:327: Connecting to IMAP server
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:918: scheduler is running
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/location.rs:746: Location loop is waiting for 24h 0m 0s or interrupt
[26.11.2024, 22:24] 💙 [1] src/ephemeral.rs:589: Ephemeral loop waiting for deletion in 24h 0m 0s or interrupt
[26.11.2024, 22:24] 💙 [1] src/contact.rs:1850: Recently seen loop waiting for 24h 0m 0s or interrupt
[26.11.2024, 22:24] 💙 [1] src/smtp.rs:512: Selected rows from SMTP queue: [].
[26.11.2024, 22:24] 💙 [1] src/imap.rs:342: IMAP trying to connect to nine.testrun.org:993:tls.
[26.11.2024, 22:24] 💙 [1] src/imap.rs:342: IMAP trying to connect to nine.testrun.org:993:tls.
[26.11.2024, 22:24] 💙 [1] src/smtp.rs:619: Sending MDNs.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:139: No memory-cached DNS resolution for nine.testrun.org available, waiting for the resolver.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:139: No memory-cached DNS resolution for nine.testrun.org available, waiting for the resolver.
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:791: SMTP fake idle started.
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:819: SMTP has no messages to retry, waiting for interrupt.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 2a01:4f8:241:4ce8::2.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 2a01:4f8:241:4ce8::2.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 116.202.233.236.
[26.11.2024, 22:24] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 116.202.233.236.
[26.11.2024, 22:24] 💙 [1] src/imap/client.rs:122: Attempting IMAP connection to nine.testrun.org (116.202.233.236:993).
[26.11.2024, 22:24] 💙 [1] src/imap/client.rs:122: Attempting IMAP connection to nine.testrun.org (116.202.233.236:993).
[26.11.2024, 22:24] 💙 [1] src/imap.rs:379: Logging into IMAP server with LOGIN.
[26.11.2024, 22:24] 💙 [1] src/imap.rs:379: Logging into IMAP server with LOGIN.
[26.11.2024, 22:24] 💙 network: reachable WiFi
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:823: SMTP fake idle interrupted.
[26.11.2024, 22:24] 💙 [1] src/smtp.rs:512: Selected rows from SMTP queue: [].
[26.11.2024, 22:24] 💙 [1] src/smtp.rs:619: Sending MDNs.
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:791: SMTP fake idle started.
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:819: SMTP has no messages to retry, waiting for interrupt.
[26.11.2024, 22:24] 💙 ➡️ applicationDidBecomeActive
[26.11.2024, 22:24] 💙 Notifications: Permission granted
[26.11.2024, 22:24] 💙 Notifications: Permission granted
[26.11.2024, 22:24] 💙 [1] src/imap.rs:388: Enabling IMAP compression.
[26.11.2024, 22:24] 💙 [1] src/imap.rs:388: Enabling IMAP compression.
[26.11.2024, 22:24] 💙 Notifications: Token: dd8ff39dbce8deb643576db9e1c2784251af41088311ae30c4cf9c56461e54c1
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/imap.rs:411: Successfully logged into IMAP server
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/imap.rs:411: Successfully logged into IMAP server
[26.11.2024, 22:24] 💙 [1] src/imap.rs:546: No new emails in folder "DeltaChat".
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:24] 💙 [1] src/imap/idle.rs:44: skip idle, got interrupt
[26.11.2024, 22:24] 💙 [1] src/imap.rs:546: No new emails in folder "DeltaChat".
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/imap.rs:1500: Server supports metadata, retrieving server comment and admin contact.
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:24] 💙 [1] src/imap/idle.rs:65: DeltaChat: Idle entering wait-on-remote state
[26.11.2024, 22:24] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:24] 💙 [1] src/imap/scan_folders.rs:31: Starting full folder scan
[26.11.2024, 22:24] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:24] 💙 [1] src/imap/idle.rs:44: skip idle, got interrupt
[26.11.2024, 22:24] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:24] 💙 📡[1] connectivity changed
[26.11.2024, 22:24] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:24] 💙 [1] src/imap/idle.rs:65: INBOX: Idle entering wait-on-remote state
[26.11.2024, 22:24] 💙 ⏰ getChatMsgs: 0.0006639957427978516 s
[26.11.2024, 22:25] 💙 ➡️ Notifications: didReceiveRemoteNotification [AnyHashable("aps"): {
    "content-available" = 1;
    "mutable-content" = 0;
}]
[26.11.2024, 22:25] 💙 ➡️ app already in foreground
[26.11.2024, 22:25] 💙 [1] src/ephemeral.rs:589: Ephemeral loop waiting for deletion in 24h 0m 0s or interrupt
[26.11.2024, 22:25] 💙 [1] src/e2ee.rs:66: Peerstate for "***@testrun.org" is mutual.
[26.11.2024, 22:25] 💙 📡[1] msgs changed: 12, 742
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:823: SMTP fake idle interrupted.
[26.11.2024, 22:25] 💙 [1] src/smtp.rs:512: Selected rows from SMTP queue: [396].
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/smtp.rs:131: SMTP trying to connect to nine.testrun.org:465:tls.
[26.11.2024, 22:25] 💙 [1] src/net/dns.rs:133: Using memory-cached DNS resolution for nine.testrun.org.
[26.11.2024, 22:25] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 2a01:4f8:241:4ce8::2.
[26.11.2024, 22:25] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 116.202.233.236.
[26.11.2024, 22:25] 💙 [1] src/smtp/connect.rs:106: Attempting SMTP connection to nine.testrun.org ([2a01:4f8:241:4ce8::2]:465).
[26.11.2024, 22:25] 💙 ⏰ getChatMsgs: 0.0040209293365478516 s
[26.11.2024, 22:25] 💙 ⏰ getChatlist: 0.0047800540924072266 s
[26.11.2024, 22:25] 💙 [1] src/smtp/connect.rs:106: Attempting SMTP connection to nine.testrun.org (116.202.233.236:465).
[26.11.2024, 22:25] 💙 [1] src/smtp.rs:384: Try number 1 to send message Msg#742 (entry 396) over SMTP.
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/smtp/send.rs:57: Message len=2837 was SMTP-sent to ***@testrun.org,*********@nine.testrun.org.
[26.11.2024, 22:25] 💙 📡[1] msgs reaction/read/delivered/failed: 12, 742
[26.11.2024, 22:25] 💙 [1] src/smtp.rs:619: Sending MDNs.
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:791: SMTP fake idle started.
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:819: SMTP has no messages to retry, waiting for interrupt.
[26.11.2024, 22:25] 💙 ⏰ getChatMsgs: 0.0007170438766479492 s
[26.11.2024, 22:25] 💙 ⏰ getChatlist: 0.001194000244140625 s
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:77: INBOX: Idle has NewData ResponseData { raw: 4096, response: MailboxData(Exists(1)) }
[26.11.2024, 22:25] 💙 [1] src/imap.rs:748: 1 mails read from "INBOX".
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:77: DeltaChat: Idle has NewData ResponseData { raw: 4096, response: MailboxData(Exists(354)) }
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:25] 💙 [1] src/imap.rs:1774: "INBOX": got unsolicited response Other(ResponseData { raw: 4096, response: Data { status: Ok, code: Some(CopyUid(1721137548, [Uid(378)], [Uid(380)])), information: Some("Moved UIDs.") } })
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:65: INBOX: Idle entering wait-on-remote state
[26.11.2024, 22:25] 💙 [1] src/imap.rs:748: 1 mails read from "DeltaChat".
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:86: INBOX: Idle wait was interrupted
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:65: DeltaChat: Idle entering wait-on-remote state
[26.11.2024, 22:25] 💙 [1] src/imap.rs:1140: Marked messages 380 in folder DeltaChat as seen.
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:77: DeltaChat: Idle has NewData ResponseData { raw: 4096, response: Fetch(354, [ModSeq(698), Flags(["\\Seen", "\\Recent"])]) }
[26.11.2024, 22:25] 💙 [1] src/imap.rs:748: 0 mails read from "DeltaChat".
[26.11.2024, 22:25] 💙 [1] src/imap.rs:748: 0 mails read from "INBOX".
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:65: DeltaChat: Idle entering wait-on-remote state
[26.11.2024, 22:25] 💙 [1] src/imap/idle.rs:65: INBOX: Idle entering wait-on-remote state
[26.11.2024, 22:25] 💙 ⏰ getChatMsgs: 0.0008740425109863281 s
[26.11.2024, 22:25] 💙 ⬅️ applicationWillResignActive
[26.11.2024, 22:25] 💙 ⬅️ registering background task
[26.11.2024, 22:25] 💙 ⬅️ applicationDidEnterBackground
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 27.737728083273396
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 23.028039749944583
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 19.905358375050128
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 16.804893999826163
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 13.671701041515917
[26.11.2024, 22:25] 💙 ⬅️ remaining background time: 10.527584249852225
[26.11.2024, 22:25] 💙 ⬅️ few background time, 7.404571374878287, stopping
[26.11.2024, 22:25] 💙 [0] src/accounts.rs:281: Stopping IO for all accounts.
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:107: stopping IO
[26.11.2024, 22:25] 💙 📡[1] connectivity changed
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:429: shutting down inbox loop
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:743: shutting down simple loop
[26.11.2024, 22:25] 💙 [1] src/scheduler.rs:830: Shutting down SMTP loop.
[26.11.2024, 22:25] 💙 ⬅️ few background time, 4.25579687487334, done
[26.11.2024, 22:29] 💙 ➡️ applicationProtectedDataDidBecomeAvailable
[26.11.2024, 22:29] 💙 ➡️ applicationWillEnterForeground
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:66: starting IO
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:389: starting inbox loop
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:699: starting simple loop for Mvbox
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:756: Starting SMTP loop.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:327: Connecting to IMAP server
[26.11.2024, 22:29] 💙 [1] src/imap.rs:327: Connecting to IMAP server
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:918: scheduler is running
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/ephemeral.rs:589: Ephemeral loop waiting for deletion in 24h 0m 0s or interrupt
[26.11.2024, 22:29] 💙 [1] src/contact.rs:1850: Recently seen loop waiting for 24h 0m 0s or interrupt
[26.11.2024, 22:29] 💙 [1] src/location.rs:746: Location loop is waiting for 24h 0m 0s or interrupt
[26.11.2024, 22:29] 💙 [1] src/smtp.rs:512: Selected rows from SMTP queue: [].
[26.11.2024, 22:29] 💙 [1] src/smtp.rs:619: Sending MDNs.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:342: IMAP trying to connect to nine.testrun.org:993:tls.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:342: IMAP trying to connect to nine.testrun.org:993:tls.
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:791: SMTP fake idle started.
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:133: Using memory-cached DNS resolution for nine.testrun.org.
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:133: Using memory-cached DNS resolution for nine.testrun.org.
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:819: SMTP has no messages to retry, waiting for interrupt.
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:823: SMTP fake idle interrupted.
[26.11.2024, 22:29] 💙 [1] src/smtp.rs:512: Selected rows from SMTP queue: [].
[26.11.2024, 22:29] 💙 [1] src/smtp.rs:619: Sending MDNs.
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:791: SMTP fake idle started.
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:819: SMTP has no messages to retry, waiting for interrupt.
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 2a01:4f8:241:4ce8::2.
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 2a01:4f8:241:4ce8::2.
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 116.202.233.236.
[26.11.2024, 22:29] 💙 [1] src/net/dns.rs:179: Resolved nine.testrun.org into 116.202.233.236.
[26.11.2024, 22:29] 💙 [1] src/imap/client.rs:122: Attempting IMAP connection to nine.testrun.org (116.202.233.236:993).
[26.11.2024, 22:29] 💙 [1] src/imap/client.rs:122: Attempting IMAP connection to nine.testrun.org (116.202.233.236:993).
[26.11.2024, 22:29] 💙 ⏰ getChatlist: 0.013309001922607422 s
[26.11.2024, 22:29] 💙 [1] src/imap.rs:379: Logging into IMAP server with LOGIN.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:379: Logging into IMAP server with LOGIN.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:388: Enabling IMAP compression.
[26.11.2024, 22:29] 💙 ➡️ applicationDidBecomeActive
[26.11.2024, 22:29] 💙 [1] src/imap.rs:388: Enabling IMAP compression.
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/imap.rs:411: Successfully logged into IMAP server
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/imap.rs:411: Successfully logged into IMAP server
[26.11.2024, 22:29] 💙 [1] src/imap.rs:546: No new emails in folder "DeltaChat".
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:29] 💙 [1] src/imap/idle.rs:44: skip idle, got interrupt
[26.11.2024, 22:29] 💙 [1] src/imap.rs:546: No new emails in folder "DeltaChat".
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:29] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:29] 💙 [1] src/imap/scan_folders.rs:31: Starting full folder scan
[26.11.2024, 22:29] 💙 [1] src/imap/idle.rs:65: DeltaChat: Idle entering wait-on-remote state
[26.11.2024, 22:29] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:29] 💙 [1] src/imap/idle.rs:44: skip idle, got interrupt
[26.11.2024, 22:29] 💙 [1] src/imap.rs:546: No new emails in folder "INBOX".
[26.11.2024, 22:29] 💙 📡[1] connectivity changed
[26.11.2024, 22:29] 💙 [1] src/scheduler.rs:678: IMAP session supports IDLE, using it.
[26.11.2024, 22:29] 💙 [1] src/imap/idle.rs:65: INBOX: Idle entering wait-on-remote state

To get the full log, use Console.app on a Mac.
```

</p>
</details>

**Comment by r10s** [comment]
at a first glance to the log, it seems, "connectivity changed" is done while the apl is in foreground.

but if the app is in foreground, no notifications are shown at all on purpose (that may change wrt mentions and webxdc etc, however, currently that is the expected behaviour)

**Comment by Hocuri** [comment]
I know, but the app was in the background when the device left the airplane mode.

> just saying as on a first glance it is not clear to me what was tested

If I understood the user correctly, it's the same thing as what you tested in the video above, but no notification arrived at the end. Just with multiple hours of waiting time inbetween, their only DC contact is me so they are using DC quite infrequently. I can't ask them anymore though because the video isn't available anymore it seems.

**Comment by r10s** [comment]
> because the video isn't available anymore it seems.

the video above is still available.

but yes, we need something more reproducible, and maybe also a video to be sure it is not expected behaviour, [cmp saving-modes](https://github.com/deltachat/deltachat-ios/issues/2387#issuecomment-2457401473). i also re-read log and do not see sth. suspicious there, however, for me it is also not obvious what the timespan for "airplane  mode" was exactly.

maybe it is related to iOS 16, i have testing devices only for iOS 15 and iOS 18 here - both work as expected, @Amzd is using iOS 16 iirc.

so, unless some other find  a way to reproduce, i do not see an actionable item and would close with "can't repro"

**Comment by r10s** [comment]
closing again as the issue is stale and not reproducible. we would need some more direct feedback to re-open this issue, maybe in person.

also, there are some known flaws at https://github.com/deltachat/deltachat-ios/issues/2673 - might also be that this is somehow related, eg. that the NSE got stuck
